
server:
  port: 8400
  servlet:
    session:
      timeout: 30m

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  main:
    allow-bean-definition-overriding: false
  session:
    store-type: redis # Session store type.
    redis:
      flush-mode: on_save # Sessions flush mode.
      namespace: spring:session # Namespace for keys used to store sessions.