server:
  port: 8200

spring:
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath:mapper/*.xml # mappler.xml文件路径
  configuration:
    map-underscore-to-camel-case: true # 开启下划线到驼峰命名的映射

management:
  endpoints:
    web:
      exposure:
        include: '*' # 暴露所有接口

##消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
#service-url:
#  nacos-user-service: http://nacos-product-service
project:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
