server:
  port: 8300

management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

project:
  thread:
    core-size: 1
    max-size: 1
    keep-alive-time: 30
