server:
  port: 8200

spring:
  main:
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath:mapper/*.xml # mappler.xml文件路径
  configuration:
    map-underscore-to-camel-case: true # 开启下划线到驼峰命名的映射
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

management:
  endpoints:
    web:
      exposure:
        include: '*' # 暴露所有接口

##消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
#service-url:
#  nacos-user-service: http://nacos-product-service
project:
  thread:
    core-size: 22
    max-size: 22
    keep-alive-time: 30

logging:
  level:
    root: info
